version: "3.8"
services:
  smtp:
    image: maildev/maildev:2.0.0-beta3
    ports:
      - 9080:1080
      - 9025:1025

  database:
    image: postgres:13.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: newsletter