- name: Pull images
  docker_image:
    name: "{{ item }}"
    source: pull
    force: true
  loop: ["antoinechalifour/rss-newsletter:latest"]

- name: Ensure PG is running
  docker_container:
    name: rss_newsletter_db
    image: postgres:13.0
    state: started
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"

- name: Ensure RSS Newsletter is running
  docker_container:
    name: rss_newsletter_api
    image: antoinechalifour/rss-newsletter
    state: started
    env:
      SIMPLEJAVAMAIL_SMTP_HOST: "{{ smtp_host }}"
      SIMPLEJAVAMAIL_SMTP_PORT: ""
      SIMPLEJAVAMAIL_SMTP_USERNAME: "{{ smtp_username }}"
      SIMPLEJAVAMAIL_SMTP_PASSWORD: "{{ smtp_password }}"
      NEWSLETTER_RECIPIENT_NAME: "{{ recipient_name }}"
      NEWSLETTER_RECIPIENT_EMAIL: "{{ recipient_email }}"
      NEWSLETTER_AUTH_USERNAME: "{{ auth_username }}"
      NEWSLETTER_AUTH_PASSWORD: "{{ auth_password }}"
      MJML_USER: "{{ mjml_user }}"
      MJML_PASSWORD: "{{ mjml_password }}"
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.5:5432/newsletter
      SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
    ports:
      - "127.0.0.1:9090:8080"