# Inspired from https://medium.com/@gmaliar/generating-lets-encrypt-certificates-for-nginx-using-ansible-9fd27b90993a
- hosts: server
  become: yes
  vars:
    service_host: "newsletter.antoinechalifour.dev"
    service_admin_email: "antoine.chalifour@gmail.com"
    service_name: "newsletter"
    letsencrypt_ssl_dir: "/etc/letsencrypt/live"
  roles:
    - letsencrypt
    - reverse_proxy